config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'cars#index'

  resources :sessions, only: %i[new create] do
    collection { delete :destroy }
  end

  namespace :admin do
    resources :dealerships
    resources :cars
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?
    can :read, Car

    return unless user.admin?
    can :manage, :all

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  MONTHLY_DEPRECATION_VALUE = 0.02

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :year, presence: true, numericality: { less_than_or_equal_to: Date.current.next_year.year }

  belongs_to :dealership

  enum condition: { brand_new: 0, used: 1 }

  def deprecated_price
    @depecated_price ||= price - (price * (months_in_dealership * MONTHLY_DEPRECATION_VALUE))
  end

  def months_in_dealership
    @months_in_dealership ||= begin
      current_date = Date.current
      created_date = created_at.to_date

      (current_date.month + current_date.year * 12) - (created_date.month + created_date.year * 12).abs
    end
  end
end

app/models/dealership.rb
# frozen_string_literal: true

class Dealership < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password :password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  enum role: { general: 0, admin: 1 }
end

app/controllers/admin/application_controller.rb
# frozen_string_literal: true

module Admin
  class ApplicationController < ::ApplicationController

    protected

    def authenticate!
      super and return if current_user.blank?

      head :unauthorized unless current_user.admin?
    end
  end
end

app/controllers/admin/cars_controller.rb
# frozen_string_literal: true

module Admin
  class CarsController < Admin::ApplicationController
    before_action :set_variables, only: %i[new edit]
    before_action :set_car, only: %i[edit update destroy]

    def index
      @cars = Car.joins(:dealership).includes(:dealership)
    end

    def new
      @car = Car.new
    end

    def create
      @car = Car.new(permitted_params)

      if @car.save
        redirect_to admin_cars_path, notice: t('.created')
      else
        flash[:errors] = @car.errors.full_messages.to_sentence
        render :new
      end
    end

    def edit; end

    def update
      redirect_to admin_cars_path, notice: t('.updated') and return if @car.update(permitted_params)

      render :edit
    end

    private

    def permitted_params
      params.require(:car).permit(:name, :condition, :dealership_id, :price)
    end

    def set_car
      @car = Car.find(params[:id])
    end

    def set_variables
      @conditions = Car.conditions.keys.map { |k| [Car.human_attribute_name(k), k] }
      @dealerships = Dealership.select(:id, :name)
    end
  end
end

app/controllers/admin/dealerships_controller.rb
# frozen_string_literal: true

module Admin
  class DealershipsController < ApplicationController
    before_action :set_dealership, only: %i[edit update destroy]

    def index
      @dealerships = Dealership.all
    end

    def new
      @dealership = Dealership.new
    end

    def create
      @dealership = Dealership.new(permitted_params)

      if @dealership.save
        redirect_to admin_dealerships_path, notice: t('.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @dealership.update(permitted_params)
        redirect_to admin_dealerships_path, notice: t('.updated')
      else
        flash[:error] = @dealership.errors.full_messages.to_sentence
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      redirect_to admin_dealerships_path, notice: t('.deleted') if @dealership.destroy
    end

    private

    def permitted_params
      params.require(:dealership).permit(:name)
    end

    def set_dealership
      @dealership = Dealership.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate!
  helper_method :current_user

  def warden
    request.env['warden']
  end

  def current_user
    warden.user
  end

  protected

  def authenticate!
    redirect_to new_session_path, notice: t('flash.unauthenticated') if current_user.blank?
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  def index
    @cars = Car.all
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authenticate!

  def new; end

  def create
    if warden.authenticate(:session)
      redirect_to root_path
    else
      redirect_to new_session_path, flash: { error: t('flash.login_fail') }
    end
  end

  def destroy
    warden.logout and redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/cars/_form.html.erb
<h4 class="display-4"><%= title %></h4>


<%= simple_form_for [:admin, @car], html: { class: 'form-control', 'data-turbo': false } do |f| %>
  <%= f.input :name %>
  <%= f.input :condition, collection: @conditions %>
  <%= f.input :dealership_id, collection: @dealerships %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/admin/cars/edit.html.erb
<%= render partial: 'form', locals: { title: t('.edit_car'), url: admin_car_path } %>

app/views/admin/cars/index.html.erb
<h4 class="display-4">Cars</h3>

<table class="table">
  <thead>
    <tr>
      <th><%= Car.human_attribute_name(:name) %></th>
      <th><%= Car.human_attribute_name(:condition) %></th>
      <th><%= Car.human_attribute_name(:price) %></th>
      <th><%= Car.human_attribute_name(:dealership) %></th>
      <th><%= t('.actions') %></td>
    </tr>
  </thead>
  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= Car.human_attribute_name(car.condition) %></td>
        <td><%= car.price %></td>
        <td><%= car.dealership.name %></td>
        <td>
          <%= link_to 'Edit', edit_admin_car_path(car) %>
          <%= link_to 'Destroy', admin_car_path(car), method: :delete, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/cars/new.html.erb
<%= render partial: 'form', locals: { title: t('.new_car'), url: admin_cars_path } %>

app/views/admin/dealerships/_form.html.erb
<%= simple_form_for [:admin, @dealership], url: url, data: { turbo: false } do |f| %>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New dealership</h5>
      </div>
      <div class="modal-body">
        <%= f.input :name, placeholder: :name %>
      </div>
      <div class="modal-footer">
        <%= f.submit :send, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/dealerships/edit.html.erb
<%= render partial: 'form', locals: { url: admin_dealership_path, title: t('.edit_dealership') } %>

app/views/admin/dealerships/index.html.erb
<div class="d-flex justify-content-between">
  <h4 class="display-4 align-self-center"">Dealerships</h3>

  <div class="align-self-center justify-content-end">
    <%= link_to 'New dealer', new_admin_dealership_path, class: 'btn  btn-primary btn-xs', data: { turbo_frame: 'dealerships_frame' } %>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th><%= Dealership.human_attribute_name(:name) %></th>
      <th><%= Dealership.human_attribute_name(:created_at) %></th>
      <th><%= t('.actions') %></td>
    </tr>
  </thead>
  <tbody>
    <% @dealerships.each do |dealership| %>
      <tr>
        <td><%= dealership.name %></td>
        <td><%= l dealership.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_admin_dealership_path(dealership) %>
          <%= link_to 'Destroy', admin_dealership_path(dealership), data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/dealerships/new.html.erb
<%= turbo_frame_tag 'dealerships_frame' do %>
  <%= render partial: 'form', locals: { url: admin_dealerships_path, title: t('.new_dealership') } %>
<% end %>

app/views/cars/index.html.erb
<h4 class="display-4">Cars</h4>

<table class="table">
  <thead>
    <tr>
      <th>Car name</th>
      <th>Price</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%= car.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarSales</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render Layout::NavbarComponent.new(current_user: current_user) %>
    <%= render Layout::FlashComponent.with_collection(flash.to_a) %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dealerships
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t('navbar.create_dealership'), new_admin_dealership_path, class: 'dropdown-item' %>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>